# Default height and ascent for emotes
default-height: 11
default-ascent: 9

# Default namespace for the emotes, normally the path is <namespace>:<folder>/<emote>.png
default-namespace: "minecraft"
default-folder: "emotes"
default-font: "emote"

default-gif-namespace: "minecraft"
default-gif-folder: "gifs"
default-gif-font: "gif"

# Recommended to switch this to MODERN on 1.19+ servers
# Allowed types are: LEGACY, MODERN
negative-space-type: LEGACY
negative-space-font: "space"
negative-space-texture: "space:font/space.png"

messages:
  no-emote: ""
  no-gif: "&cGIFs are reserved for the server's Patreon supporters."

# Format is "[<font>|]name[&<KLMNO>] [namespace] [height ascent]"
# name is the title of the emote in-game. They should only contain [a-zA-Z0-9_]
# namespace is the relative path starting from the /assets/minecraft/textures/ folder. It is emotes/<emote>.png by default.
# height is height in pixels
# ascent is how far upwards the picture should be moved. It must not be greater than height
emotes:
- "aqua_chibi"
- "aqua_big emotes/aqua_chibi.png 64 64"
- "aqua"
- "BK"
- "bonegun"
- "bonethink"
- "emoji_38"
- "fork"
- "nikounamused"
- "ozensmug"
- "pepewhy"
- "Regg"
- "rikoangry"
- "rikoeyes"
- "shrugsmug"
- "siggy"
- "yeeko"
- "YeEkO emotes/yeeko_alternative.png"

gifs:
  amogusdumpy:
    framecount: 8
    width: 12
#    namespace: "minecraft"
#    folder: "gifs"
#    font: "amogus"
#    height: 11
#    ascent: 9
