name: BondrewdLikesHisEmotes
main: io.github.bananapuncher714.bondrewd.likes.his.emotes.BondrewdLikesHisEmotes
version: 1.1.3
description: Custom emote translater for Mine in Abyss
api-version: 1.13
softdepend:
- "Viaversion"
commands:
  emote:
    description: View all of Bondrewd's favorite emotes
