name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - run: cat $HOME/.m2/settings.xml
    - uses: derongan/nmsaction@v1
      with:
        rev: 1.15.2
    - run: cat $HOME/.m2/settings.xml
    - uses: derongan/nmsaction@v1
      with:
        rev: 1.16.1
    - name: Install nms into m2
      run: mkdir -p $HOME/.m2/repository && cp -a nms-build/.m2/repository/. $HOME/.m2/repository
    - name: Build with Maven
      run: mvn clean package
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: package
        path: BondrewdLikesHisEmotes/target/final
